-- 1. Agregar columna 'turno' a produccion (Diurno / Nocturno)
ALTER TABLE IF EXISTS produccion ADD COLUMN IF NOT EXISTS turno text;

-- 2. Crear tabla para Reportes de Turno
CREATE TABLE IF NOT EXISTS public.reportes_turno (
    id bigint generated by default as identity primary key,
    fecha date not null,
    turno text not null,
    supervisor text,
    dosificador text,
    baches_dosificados integer,
    observaciones text,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    UNIQUE(fecha, turno)
);

-- Si tienes Row Level Security (RLS) habilitado, aseguramos políticas públicas para interactuar:
ALTER TABLE public.reportes_turno ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all actions for everyone on reportes_turno" ON public.reportes_turno
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);
