-- ══════════════════════════════════════════════════════════════════
-- MIGRACIÓN: MÓDULO DE FACTURACIÓN V2
-- Ejecutar en Supabase SQL Editor
-- ══════════════════════════════════════════════════════════════════

-- 1. Tabla de Pedidos (cabecera)
CREATE TABLE IF NOT EXISTS public.pedidos (
    id bigint generated by default as identity primary key,
    num_pedido text,                          -- Nullable solo si estado='PENDIENTE PV'
    num_remision integer,                     -- FK lógico a despachos.num_remision (NULL para anticipados)
    cliente_id integer references public.maestro_clientes(codigo_sap),
    codigo_cliente integer,                   -- Snapshot del codigo_sap del cliente
    nombre_cliente text,                      -- Snapshot del nombre
    fecha_despacho date,                      -- Fecha del despacho/remisión
    estado text not null default 'PENDIENTE LIBERACIÓN'
        check (estado in (
            'PENDIENTE LIBERACIÓN',
            'PENDIENTE PAGO',
            'PENDIENTE PV',
            'LIBERADO',
            'VERIFICAR PEDIDO',
            'FACTURADO'
        )),
    es_anticipado boolean default false,      -- True para facturación anticipada sin remisión
    pedido_relacionado_id bigint references public.pedidos(id),
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- 2. Tabla de Detalle del Pedido (una fila por OP seleccionada)
CREATE TABLE IF NOT EXISTS public.pedido_detalle (
    id bigint generated by default as identity primary key,
    pedido_id bigint not null references public.pedidos(id) on delete cascade,
    op integer not null,                       -- lote de programacion
    codigo_alimento integer,                   -- Snapshot: codigo_sap del alimento
    referencia text,                           -- Snapshot: nombre/descripción del alimento
    bultos_despachados integer not null default 0,
    bultos_pedido integer not null default 0,
    kg_pedido numeric generated always as (bultos_pedido * 40) stored
);

-- 3. Tabla de Facturas
CREATE TABLE IF NOT EXISTS public.facturas (
    id bigint generated by default as identity primary key,
    num_factura text,
    num_entrega text,
    fecha_facturacion date,
    estado text not null default 'FACTURADA'
        check (estado in ('FACTURADA', 'ANULADA')),
    created_at timestamptz default now()
);

-- 4. Tabla pivote Factura ↔ Pedido (M:N)
CREATE TABLE IF NOT EXISTS public.factura_pedidos (
    id bigint generated by default as identity primary key,
    factura_id bigint not null references public.facturas(id) on delete cascade,
    pedido_id bigint not null references public.pedidos(id),
    unique(factura_id, pedido_id)
);

-- 5. Tabla para Orden SAP por OP (cache único)
CREATE TABLE IF NOT EXISTS public.orden_sap_op (
    id bigint generated by default as identity primary key,
    op integer not null unique,
    orden_sap text not null
);

-- ══════════════════════════════════════════════════════════════════
-- RLS POLICIES (acceso público para la app)
-- ══════════════════════════════════════════════════════════════════

ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_pedidos_all" ON public.pedidos FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.pedido_detalle ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_pedido_detalle_all" ON public.pedido_detalle FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.facturas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_facturas_all" ON public.facturas FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.factura_pedidos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_factura_pedidos_all" ON public.factura_pedidos FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.orden_sap_op ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public_orden_sap_op_all" ON public.orden_sap_op FOR ALL TO public USING (true) WITH CHECK (true);

-- ══════════════════════════════════════════════════════════════════
-- REALTIME
-- ══════════════════════════════════════════════════════════════════

ALTER PUBLICATION supabase_realtime ADD TABLE pedidos, pedido_detalle, facturas, factura_pedidos;

-- ══════════════════════════════════════════════════════════════════
-- INDEX para consultas frecuentes
-- ══════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON public.pedidos(estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_num_remision ON public.pedidos(num_remision);
CREATE INDEX IF NOT EXISTS idx_pedido_detalle_pedido_id ON public.pedido_detalle(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_detalle_op ON public.pedido_detalle(op);
CREATE INDEX IF NOT EXISTS idx_factura_pedidos_factura ON public.factura_pedidos(factura_id);
CREATE INDEX IF NOT EXISTS idx_factura_pedidos_pedido ON public.factura_pedidos(pedido_id);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON public.facturas(estado);
